### ISSUE TITLE
warning: directory not found for option '-L/Users/qianfannew1/Downloads/PLShortVideoKit-master/ShortVideoUIDemo/ShortVideo/Effects/FaceUnity/FaceUnity-SDK-iOS'

### ISSUE THREAD

**Issue by makehapi** [pili-engineering/PLShortVideoKit#103]
ld: warning: directory not found for option '-L/Users/qianfannew1/Downloads/PLShortVideoKit-master/ShortVideoUIDemo/ShortVideo/Effects/FaceUnity/FaceUnity-SDK-iOS'
ld: warning: ignoring file /Users/qianfannew1/Downloads/PLShortVideoKit-master/ShortVideoUIDemo/Pods/Nama/FaceUnity-SDK-iOS-v6.4.1/libnama.a, building for iOS-armv7 but attempting to link with file built for unknown-unsupported file format ( 0x76 0x65 0x72 0x73 0x69 0x6F 0x6E 0x20 0x68 0x74 0x74 0x70 0x73 0x3A 0x2F 0x2F )
Undefined symbols for architecture armv7:
  "_fuGetModuleCode", referenced from:
      -[FUManager setupItemDataSource] in FUManager.o
  "_fuGetSystemError", referenced from:
      -[FUManager getError] in FUManager.o
  "_fuGetSystemErrorString", referenced from:
      -[FUManager getError] in FUManager.o
  "_fuDeleteTexForItem", referenced from:
      -[FUManager setEspeciallyItemParamImage:group_points:group_type:] in FUManager.o
  "_fuLoadTongueModel", referenced from:
      ___17-[FUManager init]_block_invoke in FUManager.o
  "_OBJC_CLASS_$_FURenderer", referenced from:
      __OBJC_$_CATEGORY_FURenderer_$_header in FURenderer+header.o
      objc-class-ref in FUManager.o
  "_fuItemSetParamd", referenced from:
      ___38-[FUManager loadMakeupBundleWithName:]_block_invoke in FUManager.o
      ___43-[FUManager setMakeupItemParamImage:param:]_block_invoke in FUManager.o
      ___42-[FUManager setMakeupItemIntensity:param:]_block_invoke in FUManager.o
      -[FUManager setMakeupItemLipstick:] in FUManager.o
      -[FUManager setPosterItemParamImage:photo:photoLandmarks:warpValue:] in FUManager.o
      -[FUManager setEspeciallyItemParamImage:group_points:group_type:] in FUManager.o
  "_fuItemSetParamdv", referenced from:
      -[FUManager setMakeupItemLipstick:] in FUManager.o
      -[FUManager setPosterItemParamImage:photo:photoLandmarks:warpValue:] in FUManager.o
      -[FUManager setEspeciallyItemParamImage:group_points:group_type:] in FUManager.o
  "_fuSetDefaultOrientation", referenced from:
      -[FUManager init] in FUManager.o
      -[FUManager renderItemsToPixelBuffer:] in FUManager.o
  "_fuCreateTexForItem", referenced from:
      ___43-[FUManager setMakeupItemParamImage:param:]_block_invoke in FUManager.o
      -[FUManager setPosterItemParamImage:photo:photoLandmarks:warpValue:] in FUManager.o
      -[FUManager setEspeciallyItemParamImage:group_points:group_type:] in FUManager.o
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Showing All Errors Only
Undefined symbol: _fuGetModuleCode

Undefined symbol: _fuGetSystemError

Undefined symbol: _fuGetSystemErrorString

Undefined symbol: _fuDeleteTexForItem

Undefined symbol: _fuLoadTongueModel

Undefined symbol: _OBJC_CLASS_$_FURenderer

Undefined symbol: _fuItemSetParamd

Undefined symbol: _fuItemSetParamdv

Undefined symbol: _fuSetDefaultOrientation

Undefined symbol: _fuCreateTexForItem

**Comment by makehapi** [comment]
![WeChat885701f430cb3823287e4b786c9fdf1b](https://user-images.githubusercontent.com/12839331/85093341-995d1a00-b21e-11ea-8463-4e010e38abf8.png)

**Comment by makehapi** [comment]
https://user-images.githubusercontent.com/12839331/85093403-c4e00480-b21e-11ea-8570-2597f6de86ea.jpg

**Comment by yellowMan1** [comment]
请问你解决了吗
