### ISSUE TITLE
3.2.0 模拟器跑不起来

### ISSUE THREAD

**Issue by FoneG** [pili-engineering/PLShortVideoKit#117]
ld: symbol(s) not found for architecture x86_64

![截屏2020-10-16 下午12 07 58](https://user-images.githubusercontent.com/15395364/96211946-3d29bd00-0fa8-11eb-8df1-dc50e9b6d9b7.png)

**Comment by Kivenhaoyu** [comment]
当前版本分真机和真机+模拟器版本，可以 pod 接入真机+模拟器版本

**Comment by Tuccuay** [comment]
@Kivenhaoyu 模拟器版本的 pod 在哪里呢？
