### ISSUE TITLE
支持多个PLShortVideoRecorder，对应多个短视频"工作区"？

### ISSUE THREAD

**Issue by jk234ert** [pili-engineering/PLShortVideoKit#12]
目前从API上看，似乎短视频录制不能创建多个短视频"工作区"？

比如我的应用需要允许用户创建多个带视频的post，需要根据post ID区分对应每个post的video assets

能不能创建 `PLShortVideoRecorder ` 时增加一个`identifier`参数，不同的`identifier`创建的recorder有单独的assets？目前的结构似乎只能同时存在一个短视频录制'工作区'

**Comment by lawder** [comment]
每个 PLShortVideoRecorder 生成的 video assets 都是单独的，你创建 PLShortVideoRecorder 时自己区分一下就好了。
