### ISSUE TITLE
PLShortVideoKit和PLMediaStreamingKit同时使用的冲突

### ISSUE THREAD

**Issue by ticsmatic** [pili-engineering/PLShortVideoKit#13]
使用Pod的方式加上直播和短视频，编译后报符号重复引用的错误。
具体的文件是"PLShortVideoKit/Pod/Library/libMuseProcessor.a"和："PLMediaStreamingKit/Pod/Library/libPLMediaStreamingKit.a"内部会有重复的编译文件，如何解决

**Comment by depthlove** [comment]
删除 PLShortVideoKit/Pod/Library/libMuseProcessor.a ，以及 Pods-xxx.debug.xcconfig、Pods-xxx.release.xcconfig 中的 -l"MuseProcessor"，即可解决库重复导致的冲突问题

**Comment by depthlove** [comment]
从 1.4.0 版本开始，可以使用 https://github.com/pili-engineering/PLShortVideoKit/blob/master/README.md 中提到的方法，更方便、简单地解决此冲突问题。

target 'TargetName' do
  pod 'PLShortVideoKit/ex-libMuseProcessor'
end
