### ISSUE TITLE
1.4.1 版本找不到调节曝光参数的地方

### ISSUE THREAD

**Issue by machinefixer** [pili-engineering/PLShortVideoKit#20]
PLShortVideoRecorder.h 里找不到文档里所说的曝光调节功能相关的接口。

**Comment by depthlove** [comment]
会在后续版本暴露该接口

**Comment by machinefixer** [comment]
@depthlove 另外是否能给手动聚焦增加两个像这样的回调：willBeginFocusAtPoint:(CGPoint)point, didFocusAtPoint:(CGPoint)point，谢谢。

**Comment by anhaoxiong** [comment]
@machinefixer 内部已经自动适配曝光参数，另外也暴露了 AVCaptureDeviceInput 参数，如果对 SDK 内部曝光效果不满意，可以自行设定曝光参数
