### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by lichunhuan** [pili-engineering/PLShortVideoKit#22]
ld: warning: directory not found for option '-L/Users/apple/Downloads/PLShortVideoKit-master/Example/PLShortVideoKitDemo/Librarys'
ld: warning: directory not found for option '-F/Users/apple/Downloads/PLShortVideoKit-master/Example/PLShortVideoKitDemo/Librarys'
ld: framework not found IOSurface for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

下载下来的dome怎么报这个错

**Comment by depthlove** [comment]
@lichunhuan 
通过以下方式下载的demo是正常的
（1）clone 工程的方式
（2）在 https://github.com/pili-engineering/PLShortVideoKit/releases 下载最新的 demo

**Comment by yuhangjob** [comment]
@depthlove 我也遇到同样的问题,下载最新的demo运行时也报同样的错误,请问一下有没有七牛的短视频问题的qq群?

**Comment by depthlove** [comment]
@lichunhuan @LiuYuHangNB demo 在 Xcode 9 环境下编译并修改过，需要使用 Xcode 9 才可编译通过。
在 Xcode 8 上会报错：ld: framework not found IOSurface for architecture arm64

**Comment by njwangchuan** [comment]
@lichunhuan 

ld: warning: directory not found for option '-L/Users/njwangchuan/Library/Developer/Xcode/DerivedData/PLShortVideoKitDemo-anoeobhqxknwwtfcxjexfrpmwizq/Build/Products/Debug-iphonesimulator/HappyDNS'
ld: warning: directory not found for option '-L/Users/njwangchuan/Library/Developer/Xcode/DerivedData/PLShortVideoKitDemo-anoeobhqxknwwtfcxjexfrpmwizq/Build/Products/Debug-iphonesimulator/Masonry'
ld: warning: directory not found for option '-L/Users/njwangchuan/Library/Developer/Xcode/DerivedData/PLShortVideoKitDemo-anoeobhqxknwwtfcxjexfrpmwizq/Build/Products/Debug-iphonesimulator/Qiniu'
ld: library not found for -lHappyDNS
clang: error: linker command failed with exit code 1 (use -v to see invocation)

模拟器目录下并没有HappyDNS、Masonry和Qiniu，网上找了一些删除search path的方法，没有解决问题

**Comment by njwangchuan** [comment]
@lichunhuan 已经找到问题了。xcode导入的工程不对，需要导入.xcworkspace

**Comment by hb-chen** [comment]
@depthlove 是必须Xcode9吗？

**Comment by depthlove** [comment]
@hb-chen 因为用的 Xcode 9.0 以上版本打包的短视频 SDK framework，用 Xcode 9.0 以下版本，比如 Xcode 8.x.x 就会编译出错
