### ISSUE TITLE
Demo首次启动闪退 PLShortVideoKitDemo[2276:1216907] *** -[NSKeyedUnarchiver initForReadingWithData:]: data is NULL

### ISSUE THREAD

**Issue by danfeng** [pili-engineering/PLShortVideoKit#25]
Demo首次启动闪退 
PLShortVideoKitDemo[2276:1216907] *** -[NSKeyedUnarchiver initForReadingWithData:]: data is NULL
PLShortVideoKitDemo[2276:1216907] -- didStartRecordingToOutputFileAtURL: --
PLShortVideoKitDemo[2276:1216907] start recording fileURL: file:///var/mobile/Containers/Data/Application/xxxxxxx-3A31-40C6-90A1-57DBEF83DE3D/Documents/PLShortVideoRootFolder/PLShortVideo/20171110143122.mp4
error: auth failed

**Comment by depthlove** [comment]
@danfeng "error: auth failed" 表明 bundle id 不在白名单内，没有通过鉴权就会 crash。

本短视频 SDK 需授权方可使用，可通过 400-808-9176 转 2 号线联系七牛商务咨询，或者 通过工单（https://support.qiniu.com/?ref=developer.qiniu.com） 联系七牛的技术支持。

**Comment by angelen10** [comment]
在 iOS 10，iPhone 7 那里报错：
-[NSKeyedUnarchiver initForReadingWithData:]: data is NULL

但是我这个 App 已经是授权了的，而且在其他的系统版本没有发现这个问题（最新的 SDK）
