### ISSUE TITLE
UI 操作在后台调用导致 Crash

### ISSUE THREAD

**Issue by VincentSit** [pili-engineering/PLShortVideoKit#26]
看一下这个是我的问题还是 SDK 的问题? 

`PLShortVideoRecorder +startCaptureSession` 会崩溃.

<img width="2556" alt="qq20171121-210328 2x" src="https://user-images.githubusercontent.com/4084679/33074001-9bb84716-ceff-11e7-8e50-a9542a6eb61e.png">

**Comment by depthlove** [comment]
@VincentSit 最新版解决了这个问题
