### ISSUE TITLE
报错？怎么解决这个

### ISSUE THREAD

**Issue by linxuanzhao** [pili-engineering/PLShortVideoKit#3]
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_PLSAudioConfiguration", referenced from:
      objc-class-ref in RecordViewController.o
  "_OBJC_CLASS_$_PLSVideoConfiguration", referenced from:
      objc-class-ref in RecordViewController.o
  "_OBJC_CLASS_$_PLShortVideoSession", referenced from:
      objc-class-ref in RecordViewController.o
  "_OBJC_CLASS_$_PLSFile", referenced from:
      objc-class-ref in EditViewController.o
  "_OBJC_CLASS_$_PLSPlayer", referenced from:
      objc-class-ref in EditViewController.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by linxuanzhao** [comment]
查不到原因

**Comment by lawder** [comment]
不好意思，发布的时候漏了带上模拟器的支持了，后续版本会加上。真机调试是正常的。@linxuanzhao

**Comment by lawder** [comment]
1.0.1 已解决。
