### ISSUE TITLE
pod install 的时候报错 Remote branch v1.0.1 not found in upstream origin

### ISSUE THREAD

**Issue by figure-ai** [pili-engineering/PLShortVideoKit#30]
我在使用cocoapod集成PLShortVideoKit的时候发生了Remote branch v1.0.1 not found in upstream origin的错误
我试图通过搜索引擎还有查看官方文档但是都没有找到解决问题的方法
我通过执行pod search PLShortVideoKit 是可以找到对应的版本好的
所以我不清除问题出在哪了
你们能帮我看一下吗
我的cocoapod版本是1.3.1
ruby版本是2.4.1
错误详细信息如下
Installing PLShortVideoKit (1.0.1)

[!] Error installing PLShortVideoKit
[!] /usr/bin/git clone https://github.com/pili-engineering/PLShortVideoKit.git /var/folders/6h/c2ll7w955_q1rxm16yjqv3gr0000gn/T/d20180105-995-1tam2k4 --template= --single-branch --depth 1 --branch v1.0.1

Cloning into '/var/folders/6h/c2ll7w955_q1rxm16yjqv3gr0000gn/T/d20180105-995-1tam2k4'...
warning: Could not find remote branch v1.0.1 to clone.
fatal: Remote branch v1.0.1 not found in upstream origin

**Comment by yanqiw** [comment]
+1

**Comment by yanqiw** [comment]
i fix this by use below:
pod 'PLShortVideoKit', :git => 'https://github.com/pili-engineering/PLShortVideoKit.git', :tag => 'v1.8.0'
