### ISSUE TITLE
报错Pili-ShortVideo-Authorization PLShortVideo SDK authorization status error: auth failed!

### ISSUE THREAD

**Issue by pinguo-mazhong** [pili-engineering/PLShortVideoKit#32]
第一次安装启动，已经授权使用相机了。后面有时候在运行的时候，有时候会出现闪退，xcode的console里输出：Pili-ShortVideo-Authorization PLShortVideo SDK authorization status error: auth failed!这个错误消息。这是为什么呢？（刚刚才成功运行了一次，下一次就出现这个错误了，概率性出现）

**Comment by taoyeming** [comment]
这个SDK是需要授权才能使用的，如果你们取得了七牛的授权的话就检查一下你的bundle identifier是否填错了。

**Comment by fight-ing** [comment]
为什么这个错误不是一直出现，很有偶发性。

**Comment by shadow-boy** [comment]
请问一下这个授权是七牛后台哪里设置

**Comment by depthlove** [comment]
请联系七牛的销售或者技术支持。

**Comment by Answer000** [comment]
大佬，请问解决了么？遇到同样的坑了。

**Comment by depthlove** [comment]
@AnswerXu 

https://github.com/pili-engineering/PLShortVideoKit/blob/master/README.md

5. 声明
本短视频 SDK 需授权方可使用，可通过 400-808-9176 转 2 号线联系七牛商务咨询，或者 [通过工单](https://support.qiniu.com/?ref=developer.qiniu.com) 联系七牛的技术支持。
