### ISSUE TITLE
这个SDK可以做国际化么？

### ISSUE THREAD

**Issue by guopeng1994** [pili-engineering/PLShortVideoKit#33]
怎么实现？老铁们～有知道的不？

**Comment by anhaoxiong** [comment]
您好！非常感谢你的提问。我们的这个SDK里面没有需要国际化的文字或者图片。如果有需要国际化的地方，在UI层做就可以。不知道是否解决了你的问题，如果没有。可以留下你的联系方式，我们会有人联系你帮助解决你的问题。
