### ISSUE TITLE
测试Demo运行之后到EditViewController卡住

### ISSUE THREAD

**Issue by fight-ing** [pili-engineering/PLShortVideoKit#37]
直接克隆项目到本地，编辑页面之后完全没有反应，也没有错误提示。图片合成视频也是如此~~
-[EditViewController shortVideoEditor:didReadyToPlayForAsset:timeRange:], videoProgress: 0.000000
isEditing:1, timestamp: 0.000000, videoProgress: 0.000000

**Comment by depthlove** [comment]
@fight-ing 请问用的是哪个版本，运行 demo 时有没有改 bundleid，现在问题还有出现吗？

**Comment by fight-ing** [comment]
有改bundleId，什么原因？

**Comment by depthlove** [comment]
@fight-ing 在 EditViewController.m 中视频数据回调中的抖音特效代码注释掉就正常了，根本原因是改之后的bundleid 对应的抖音特效没有被授权。

**Comment by fight-ing** [comment]
好，谢谢
