### ISSUE TITLE
pod 'PLShortVideoKit'， pod install 报错

### ISSUE THREAD

**Issue by yangjing901** [pili-engineering/PLShortVideoKit#40]
[!] Error installing PLShortVideoKit
[!] /usr/bin/git clone https://github.com/pili-engineering/PLShortVideoKit.git /var/folders/gp/3vg61tnd1lnf9102ncwxq2vc0000gn/T/d20180410-47194-gbzij9 --template= --single-branch --depth 1 --branch v1.10.0

Cloning into '/var/folders/gp/3vg61tnd1lnf9102ncwxq2vc0000gn/T/d20180410-47194-gbzij9'...
error: RPC failed; curl 18 transfer closed with outstanding read data remaining
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed

**Comment by depthlove** [comment]
Please check your network.
