### ISSUE TITLE
水印改变尺寸无效

### ISSUE THREAD

**Issue by bubbleTang** [pili-engineering/PLShortVideoKit#43]
CGSize watermarkSize = CGSizeMake(75, 25);
  watermarkSettings[PLSSizeKey] = [NSValue valueWithCGSize:watermarkSize];

改变watermarkSize大小 实际显示的水印尺寸没没有改变

**Comment by depthlove** [comment]
@bubbleTang 这个内部处理时没有按照应用外部设置的 watermarkSize 进行缩放。
