### ISSUE TITLE
presentBufferForDisplay 崩溃

### ISSUE THREAD

**Issue by stonewin540** [pili-engineering/PLShortVideoKit#46]
stackoverflow 上有同样问题，简书上也有说明 [https://www.jianshu.com/p/b408596afcac](url)；
针对于 PLShortVideoRecorder SDK 并没有提供暂停预览和恢复预览的功能，只提供一个 id 类型的 previewView，在录完一段视频的时候，退到后台再回到前台就会崩溃，我拿着 previewView 什么也做不了，提供给我还有什么意义？
本周末就要上线这个功能，这个崩溃估计不能及时解决了。。。
![screen shot 2018-04-27 at 11 15 50 am](https://user-images.githubusercontent.com/5546926/39342978-0b05fc3e-4a0d-11e8-8c3d-7ffd0a84589c.png)

**Comment by stonewin540** [comment]
好吧，我定为错了，是 PLShortVideoEditor 引起的崩溃，我拥有一个实例用来预览，所以可以通过暂停来解决问题，我错了 sorry！

**Comment by depthlove** [comment]
@stonewin540 感谢您的反馈。
