### ISSUE TITLE
选择本地视频时, 使用4k拍摄出来的视频, 会直接闪退

### ISSUE THREAD

**Issue by herobin22** [pili-engineering/PLShortVideoKit#48]

**Comment by depthlove** [comment]
@herobin22  Thank you for your feedback. We will check it.

**Comment by depthlove** [comment]
@herobin22 已经定位到具体原因了。预计在 v.1.12 及之后的版本发布。

**Comment by anhaoxiong** [comment]
@herobin22 非常感谢您的反馈，问题已在 v1.11.1 解决
