### ISSUE TITLE
UI可以适配iPhone X么?

### ISSUE THREAD

**Issue by shenguanjiejie** [pili-engineering/PLShortVideoKit#49]

**Comment by depthlove** [comment]
@shenguanjiejie  YES. The SDK supports user to make custom view.

**Comment by shenguanjiejie** [comment]
@depthlove  I hope "PLShortVideoKit" support iPhone X by default, I have no time to make a custom view 😂

**Comment by anhaoxiong** [comment]
@shenguanjiejie SDK 内部就只有一个 预览 view，没有其他的 UI，这个关于 iPhone X 的适配，只能依靠上层来处理
