### ISSUE TITLE
auth failed

### ISSUE THREAD

**Issue by bing6** [pili-engineering/PLShortVideoKit#50]
Pili-ShortVideo-Authorization PLShortVideo SDK authorization status error: auth failed!
我该如何授权？
经常因为这个问题而闪退。

**Comment by depthlove** [comment]
@bing6 You can try it.

README
https://github.com/pili-engineering/PLShortVideoKit/blob/master/README.md
5. 声明
本短视频 SDK 需授权方可使用，可通过 400-808-9176 转 2 号线联系七牛商务咨询，或者 通过工单 联系七牛的技术支持。
