### ISSUE TITLE
运行demo编译报错

### ISSUE THREAD

**Issue by iOSLaoPi** [pili-engineering/PLShortVideoKit#51]
![2018-06-06 13 24 05](https://user-images.githubusercontent.com/18502756/41018555-ed6d1776-698c-11e8-89fb-96abc5c885d2.png)

**Comment by depthlove** [comment]
@iOSLaoPi  We will update the demo to support the simulator debug.

**Comment by iOSLaoPi** [comment]
demo版本是1.9.0，cocoapods下载的版本是1.7.0，两者代码不一致，你们何时更新pods代码。我公司正在用你们的短视频，麻烦尽快统一。

**Comment by depthlove** [comment]
@iOSLaoPi 
The latest version of library and demo is v1.10.0. 

You need use
demo: https://github.com/pili-engineering/PLShortVideoKit/releases/tag/v1.10.0 
library: pod 'PLShortVideoKit', '1.10.0'

The document 
https://developer.qiniu.com/pili/sdk/3733/short-video-ios-sdk#9

**Comment by HenanMobile** [comment]
**Minmin.Sun depthlove** 文明用语，请讲普通话。
