### ISSUE TITLE
 PLSGLProgram duplicate symbol

### ISSUE THREAD

**Issue by yarshure** [pili-engineering/PLShortVideoKit#53]
duplicate symbol _OBJC_IVAR_$_PLSGLProgram.uniforms in:
    /Users/kongxiangbo/work/app-iv3/laoyuegou/Pods/PLShortVideoKit/Pod/Library/PLShortVideoKit.framework/PLShortVideoKit(PLSGLProgram.o)
duplicate symbol _OBJC_IVAR_$_PLSGLProgram.attributes in:
    /Users/kongxiangbo/work/app-iv3/laoyuegou/Pods/PLShortVideoKit/Pod/Library/PLShortVideoKit.framework/PLShortVideoKit(PLSGLProgram.o)
duplicate symbol _OBJC_IVAR_$_PLSGLProgram.vertShader in:
    /Users/kongxiangbo/work/app-iv3/laoyuegou/Pods/PLShortVideoKit/Pod/Library/PLShortVideoKit.framework/PLShortVideoKit(PLSGLProgram.o)
duplicate symbol _OBJC_IVAR_$_PLSGLProgram.fragShader in:
    /Users/kongxiangbo/work/app-iv3/laoyuegou/Pods/PLShortVideoKit/Pod/Library/PLShortVideoKit.framework/PLShortVideoKit(PLSGLProgram.o)
duplicate symbol _OBJC_IVAR_$_PLSGLProgram.program in:
    /Users/kongxiangbo/work/app-iv3/laoyuegou/Pods/PLShortVideoKit/Pod/Library/PLShortVideoKit.framework/PLShortVideoKit(PLSGLProgram.o)
duplicate symbol _OBJC_CLASS_$_PLSGLProgram in:
    /Users/kongxiangbo/work/app-iv3/laoyuegou/Pods/PLShortVideoKit/Pod/Library/PLShortVideoKit.framework/PLShortVideoKit(PLSGLProgram.o)
duplicate symbol _OBJC_METACLASS_$_PLSGLProgram in:
    /Users/kongxiangbo/work/app-iv3/laoyuegou/Pods/PLShortVideoKit/Pod/Library/PLShortVideoKit.framework/PLShortVideoKit(PLSGLProgram.o)
duplicate symbol _OBJC_IVAR_$_PLSGLProgram._vertexShaderLog in:
    /Users/kongxiangbo/work/app-iv3/laoyuegou/Pods/PLShortVideoKit/Pod/Library/PLShortVideoKit.framework/PLShortVideoKit(PLSGLProgram.o)
duplicate symbol _OBJC_IVAR_$_PLSGLProgram._fragmentShaderLog in:
    /Users/kongxiangbo/work/app-iv3/laoyuegou/Pods/PLShortVideoKit/Pod/Library/PLShortVideoKit.framework/PLShortVideoKit(PLSGLProgram.o)
duplicate symbol _OBJC_IVAR_$_PLSGLProgram._programLog in:
    /Users/kongxiangbo/work/app-iv3/laoyuegou/Pods/PLShortVideoKit/Pod/Library/PLShortVideoKit.framework/PLShortVideoKit(PLSGLProgram.o)
duplicate symbol _OBJC_IVAR_$_PLSGLProgram._initialized in:
    /Users/kongxiangbo/work/app-iv3/laoyuegou/Pods/PLShortVideoKit/Pod/Library/PLShortVideoKit.framework/PLShortVideoKit(PLSGLProgram.o)
ld: 11 duplicate symbols for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by yarshure** [comment]
我们的项目需要使用-all_load 链接参数，PLShortVideoKit 和这个参数不兼容，请尽快修复
version 1.11.0

**Comment by yarshure** [comment]
项目里用force-load xxlib 暂时跳过这个坑

**Comment by depthlove** [comment]
@yarshure 感谢反馈。我们尽快 check 这个问题。

**Comment by depthlove** [comment]
@yarshure 已解决该问题，在合适的时间点会更新 PLShortVideoKit.framework。

**Comment by anhaoxiong** [comment]
@yarshure 最新的版本 v1.11.1  已经解决这个问题，非常感谢反馈！
