### ISSUE TITLE
PLSUploaderConfiguration 如何设置使用区域的？

### ISSUE THREAD

**Issue by networkextension** [pili-engineering/PLShortVideoKit#54]
PLSUploaderConfiguration
- (instancetype)initWithToken:(NSString * _Nonnull)token
                               videoKey:(NSString * _Nullable)videoKey
                                  https:(BOOL)https
                               recorder:(NSString * _Nullable)recorder
                                 params:(NSDictionary * _Nullable)params;
这个类的params 这么设置，我们测试的时候发现upload.qiniu.com 无效，要用其他主机

**Comment by Kivenhaoyu** [comment]
能否给一下具体的设置，我们这边看一下
