### ISSUE TITLE
第一次从相册选择视频，上传前进行转码，但是转码时候直接崩溃，求解决办法

### ISSUE THREAD

**Issue by Answer000** [pili-engineering/PLShortVideoKit#57]
[[PHImageManager defaultManager] requestAVAssetForVideo:_videoAsset options:options2 resultHandler:^(AVAsset *asset, AVAudioMix *audioMix, NSDictionary *info) {
        PLShortVideoTranscoder *shortVideoTranscoder = [[PLShortVideoTranscoder alloc] initWithAsset:asset];
        shortVideoTranscoder.outputFilePreset = [_outputFilePreset integerValue];
        shortVideoTranscoder.outputFileType = PLSFileTypeMPEG4;

          // 在此处崩溃，没有转码失败的错误信息
        [shortVideoTranscoder startTranscoding];  
 
    }];

控制台打印一个错误：
2018-08-03 10:31:24:726 Dgtle[13339:4847816] [W] Pili-ShortVideo-Authorization PLShortVideo SDK authorization status error: auth failed! 
 -[PLSNoitacitnehtua requestData]_block_invoke PLSNoitacitnehtua.m:81

**Comment by depthlove** [comment]
@AnswerXu SDK 鉴权失败，可查看 https://github.com/pili-engineering/PLShortVideoKit/issues/32
