### ISSUE TITLE
大佬们，这个短视频是免费的吗

### ISSUE THREAD

**Issue by Hwangkop** [pili-engineering/PLShortVideoKit#60]
大佬们，这个短视频是免费的吗

**Comment by depthlove** [comment]
@Hwangkop 需要授权使用。

https://github.com/pili-engineering/PLShortVideoKit/blob/master/README.md

5. 声明
本短视频 SDK 需授权方可使用，可通过 400-808-9176 转 2 号线联系七牛商务咨询，或者 通过工单 联系七牛的技术支持。
