### ISSUE TITLE
the crash error

### ISSUE THREAD

**Issue by thereqwe** [pili-engineering/PLShortVideoKit#62]
Pili-ShortVideo-Authorization PLShortVideo SDK authorization status error: auth failed! 
 -[PLSNoitacitnehtua start] PLSNoitacitnehtua.m:65

**Comment by thereqwe** [comment]
权限都添加了 plist ios12

**Comment by depthlove** [comment]
@thereqwe 

可查看类似 issue：https://github.com/pili-engineering/PLShortVideoKit/issues/32

详情见 SDK 的使用文档说明：
https://github.com/pili-engineering/PLShortVideoKit/blob/master/README.md 
其中：
5. 声明
本短视频 SDK 需授权方可使用，可通过 400-808-9176 转 2 号线联系七牛商务咨询，或者 [通过工单](https://support.qiniu.com/?ref=developer.qiniu.com) 联系七牛的技术支持。

**Comment by thereqwe** [comment]
oh~那文档里可以提一句"没有权限就会crash". 不然很难联想到是因为需要授权,虽然有"auth failed".
