### ISSUE TITLE
关于sessionPreset的一点建议。

### ISSUE THREAD

**Issue by zisulu** [pili-engineering/PLShortVideoKit#63]
我看可以设置sessionPresset参数，那么为什么不提供canSetSessionPreset:的接口让外部判断是否设备支持这个sessionPresset

**Comment by anhaoxiong** [comment]
非常感谢您的反馈。我们会在近期的版本中解决这个问题。

**Comment by anhaoxiong** [comment]
@zisulu 最新版本的 v1.15.0 已经提供获取 AVCaptureSession 的接口，可以直接在外部调用 AVCaptureSession 判断 canSetSessionPreset。再次感谢你的建议

**Comment by zisulu** [comment]
> @zisulu 最新版本的 v1.15.0 已经提供获取 AVCaptureSession 的接口，可以直接在外部调用 AVCaptureSession 判断 canSetSessionPreset。再次感谢你的建议

好的。辛苦。
