### ISSUE TITLE
关于集成的几个问题。

### ISSUE THREAD

**Issue by zisulu** [pili-engineering/PLShortVideoKit#64]
我是使用Pod集成的PLShortVideoKit，有两个问题文档里面没有：
1.libMuseProcessor.a必须要手动拖入项目，美颜功能才会生效吗（实际测试是这样的）
2.我在需要使用的类中导入了#import <PLShortVideoKit/PLShortVideoKit.h>，但是在调用AVAsset+PLSExtendProperty.h这个category中的方法时闪退（unrecognized selector），是我的项目环境存在问题吗？

**Comment by anhaoxiong** [comment]
@zisulu 非常抱歉给你带来了困扰，关于第 2 个问题，需要在工程的 build setting 中的 other linker flags 下，添加 -Objc 或者  -load_all 来解决。后面我们会改进我们的文档。

**Comment by zisulu** [comment]
@anhaoxiong 我项目中本身就配置了-Objc，如果没配的话项目应该是无法运行的，但是我运行是正常的，只是在调用方法时出现闪退（unrecognized selector），所以我比较奇怪

- 我测试了一下，我不用Pod导入，直接把SDK拖进项目就是正常的

- 找到原因了。是other link flags配置的问题，因为之前项目我们添加了一些标识，导致pod添加的无法覆盖生效，现在已经好了，谢谢。

**Comment by zisulu** [comment]
@anhaoxiong 我测试了一下，我不用Pod导入，直接把SDK拖进项目就是正常的
