### ISSUE TITLE
是否有考虑提供授权状态的api？

### ISSUE THREAD

**Issue by zisulu** [pili-engineering/PLShortVideoKit#66]
我不清楚 授权过期是否会crash，但是未授权一定是会crash的。

**Comment by zisulu** [comment]
...

**Comment by depthlove** [comment]
@zisulu 您的需求，我们已考虑，后面的版本会提供相应的查询是否授权的 API 接口。

**Comment by anhaoxiong** [comment]
@zisulu 已经添加查询接口，将会在接下来的 v1.16.1 版本中提供。预计年前发布 v1.16.1

**Comment by zisulu** [comment]
> @zisulu 已经添加查询接口，将会在接下来的 v1.16.1 版本中提供。预计年前发布 v1.16.1

@anhaoxiong 好的。请问安卓的SDK是否也会添加这个接口。
