### ISSUE TITLE
我想用这个库封装一个组件,出现静态库的问题,能给个解决方法吗

### ISSUE THREAD

**Issue by jyyjkt** [pili-engineering/PLShortVideoKit#67]
PLShortVideoKit.framework
-> CNLiveUploadManager (0.0.3)
    - WARN  | source: Git SSH URLs will NOT work for people behind firewalls configured to only allow HTTP, therefore HTTPS is preferred.
    - WARN  | [iOS] license: Unable to find a license file
    - ERROR | [iOS] unknown: Encountered an unknown error (The 'Pods-App' target has transitive dependencies that include static binaries: (/private/var/folders/1r/3sdh7kh57s1fx8xvgldr296r0000gn/T/CocoaPods-Lint-20181031-99152-yv5030-CNLiveUploadManager/Pods/PLShortVideoKit/Pod/Library/PLShortVideoKit.framework and /private/var/folders/1r/3sdh7kh57s1fx8xvgldr296r0000gn/T/CocoaPods-Lint-20181031-99152-yv5030-CNLiveUploadManager/Pods/PLShortVideoKit/Pod/Library/libMuseProcessor.a)) during validation.

**Comment by anhaoxiong** [comment]
是否有试过将 PLShortVideoKit.framework 和 libMuseProcessor.a 拷贝到工程中直接使用？

**Comment by jyyjkt** [comment]
你的意识是我直接写组件的时候直接依赖拖进去是吧 好的

**Comment by jyyjkt** [comment]
share.dependency 'UMengUShare/UI'
share.dependency 'UMengUShare/Social/Sina'
share.dependency 'UMengUShare/Social/WeChat'
share.dependency 'UMengUShare/Social/QQ'
share.dependency 'UMengUShare/Social/TencentWeibo'
好多第三方都能依赖的   PLShortVideoKit依赖就报错  
我试过
 s.vendored_frameworks = 'CNLiveUploadManager/PLShortVideoKit.framework'
 s.vendored_library = 'CNLiveUploadManager/libMuseProcessor.a'
编译是通过了但是在使用的时候问题经常报错

**Comment by jyyjkt** [comment]
你们的七牛上传都是可以依赖的 而且没问题可调用
