### ISSUE TITLE
发现录制的视频，上传到服务器过后(包括Demo的七牛云服务器)，播放超级卡

### ISSUE THREAD

**Issue by huangrun** [pili-engineering/PLShortVideoKit#7]
录制了十多秒的视频，上传到七牛云上，然后拿到链接，播放，很卡，有时会卡住放不了，是因为分辨率太高了吗？尝试调了些录制参数，还是没解决。希望楼主看看啊

**Comment by depthlove** [comment]
@huangrun 麻烦给下视频文件的播放链接

**Comment by huangrun** [comment]
http://oowtvx1xy.bkt.clouddn.com/short_video_20170515140036.mp4

**Comment by depthlove** [comment]
@huangrun 原因在于使用的测试域名限速了，对于码率高的视频播放会卡。

**Comment by huangrun** [comment]
嗯嗯，新地址没问题！
