### ISSUE TITLE
 [W] Pili-ShortVideo-Authorization PLShortVideo SDK authorization status error: auth failed!    -[PLSNoitacitnehtua start] PLSNoitacitnehtua.m:65  我需要授权，我只需要用到视频裁剪，音视频合成，图片合成视频，视频拍摄美颜，的一些基础功能，授权是要交多少钱的预存？

### ISSUE THREAD

**Issue by YangKai123** [pili-engineering/PLShortVideoKit#74]
[W] Pili-ShortVideo-Authorization PLShortVideo SDK authorization status error: auth failed! 

 -[PLSNoitacitnehtua start] PLSNoitacitnehtua.m:65

我需要授权，我只需要用到视频裁剪，音视频合成，图片合成视频，视频拍摄美颜，的一些基础功能，授权是要交多少钱的预存？

**Comment by depthlove** [comment]
@YangKai123 请问是个人还是公司业务？

**Comment by depthlove** [comment]
@YangKai123 请看 https://github.com/pili-engineering/PLShortVideoKit/issues/32

**Comment by YangKai123** [comment]
我是个人的，预存多少钱得

**Comment by depthlove** [comment]
@YangKai123 

https://github.com/pili-engineering/PLShortVideoKit/blob/master/README.md

5. 声明
本短视频 SDK 需授权方可使用，可通过 400-808-9176 转 2 号线联系七牛商务咨询，或者 [通过工单](https://support.qiniu.com/?ref=developer.qiniu.com) 联系七牛的技术支持。
