### ISSUE TITLE
运行Example_TuTu时报错

### ISSUE THREAD

**Issue by lhh-sofy** [pili-engineering/PLShortVideoKit#75]
你好，下载最新代码，运行demo，编译时候报错。错误如图所示.
![wechatimg469](https://user-images.githubusercontent.com/13582183/50805071-bbfdba80-132b-11e9-83fd-4c5146f95c96.jpeg)

**Comment by anhaoxiong** [comment]
真机试试，部分 framework 不包含模拟器版本

**Comment by lhh-sofy** [comment]
好的，多谢，已经解决了，是模拟器不支持。
