### ISSUE TITLE
授权后黑屏，重新进入后开始录制crash

### ISSUE THREAD

**Issue by mmx1101** [pili-engineering/PLShortVideoKit#8]
控制台打印error: auth failed

**Comment by Jhuster** [comment]
@mmx1101 请问您的应用 bundle id 是？

**Comment by mmx1101** [comment]
bundle id：com.ymhd.app.rois

**Comment by Jhuster** [comment]
@mmx1101 我们并没有收到这个 ID 的配置申请，麻烦联系下与你们对接的商务

**Comment by mmx1101** [comment]
目前只是运行你们的demo，出现首次访问相机权限弹框后黑屏，录制过程crash出现概率还是挺高的

**Comment by Jhuster** [comment]
@mmx1101 我们的 demo 不改包名的话，不会有 `auth failed` 错误，你把完整的 carsh log 发出来看看

**Comment by depthlove** [comment]
@mmx1101 v1.3.0 做了修复

**Comment by lilthree** [comment]
1.5.0 仍然有这个问题

**Comment by depthlove** [comment]
@lilthree 请将报错信息提供下（控制台打印、堆栈信息等），越详细越有助于我们及时解决您的问题

**Comment by lilthree** [comment]
控制台打印error: auth failed，然后crash，没有其他信息

**Comment by depthlove** [comment]
@lilthree 这个打印说明，鉴权失败，没有添加白名单。你可以在技术支持群里说明情况，或者找你们公司对接sdk 的相关负责人，让七牛这边开通白名单。
