### ISSUE TITLE
initWithVideoConfiguration

### ISSUE THREAD

**Issue by hYRamos** [pili-engineering/PLShortVideoKit#83]
PLShortVideoRecorder 初始化方法闪退，调试时直接crash，无log提示

**Comment by HeraShowFeng** [comment]
可以参照下 PLShortVideoKitDemo 中的示例进行初始化使用。

**Comment by isdotjim** [comment]
搭个车...
想邀请Repo作者来w3c.group创建项目的对应小组。w3c.group是类似知识星球的社群工具，小组可设置为付费且有赞助功能，同时也是一个区块链主导的创作者社区。这是相关介绍：
http://t.cn/Ai1vLcCU
http://t.cn/Ai1vLcCG
http://t.cn/Ai1vLcCA
