### ISSUE TITLE
PLShortVideoEditor编辑之后调用stopEditing方法  completionBlock回调不会被执行  

### ISSUE THREAD

**Issue by jin1050260** [pili-engineering/PLShortVideoKit#85]
PLShortVideoEditor编辑之后调用stopEditing方法  completionBlock回调不会被执行   什么情况能触发回调执行呢？

**Comment by Kivenhaoyu** [comment]
你好
1 关于 stopEditing，该 API 功能为停止实时预览编辑效果，不会导出文件，文件需要用 PLSAVAssetExportSession 方法来设置导出
2 completionBlock 是老版本的接口，我们为了兼容之前版本，所以留下的，不做使用
