### ISSUE TITLE
某些个视频转码后出现绿边

### ISSUE THREAD

**Issue by HongxiangShe** [pili-engineering/PLShortVideoKit#86]

**Comment by Kivenhaoyu** [comment]
你好，麻烦提供一下具体的信息，尽量包涵下面几项，我们收到后，尽快定位
1. SDK 版本   
2. 复现问题的手机型号，系统   
3. 复现流程    
4. demo 中是否可复现   
5. 错误 log   
6. 如果相关视频有问题，麻烦提供具体的视频
