### ISSUE TITLE
横屏拍照的图片保存到相册后方向不对

### ISSUE THREAD

**Issue by Lee-Wang-Jing** [pili-engineering/PLShortVideoKit#90]
查看好像不是拍照，没有imageOrientation，好像是截屏~ 麻烦问一下该如何处理

**Comment by Lee-Wang-Jing** [comment]
使用的是截屏的方法

**Comment by HeraShowFeng** [comment]
需要确定 PLSVideoConfiguration 下的 videoOrientation 采集旋转方向，是否与需求方向一致
