### ISSUE TITLE
编辑过的视频时间线错误问题

### ISSUE THREAD

**Issue by yz7805325** [pili-engineering/PLShortVideoKit#92]
EditViewController.m文件,417行左右mediaInfo没有配置startTime,默认是0,会导致编辑过的本地视频,时间线开始动画错误!!!!

**Comment by HeraShowFeng** [comment]
麻烦提供下 sdk 的版本、复现设备系统 iOS 版本、本地视频信息（分辨率、帧率）以及时间先动画错误的具体情况描述，我们可根据以上信息做进一步复现排查
