### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by baiRookie** [pili-engineering/PLShortVideoKit#93]
ld: warning: ignoring file /Users/KOOSPUR/Documents/代码托管/tennis/CoollangTennisBall/Pods/PLShortVideoKit/Pod/Library/Profession/PLShortVideoKit.framework/PLShortVideoKit, missing required architecture x86_64 in file /Users/KOOSPUR/Documents/代码托管/tennis/CoollangTennisBall/Pods/PLShortVideoKit/Pod/Library/Profession/PLShortVideoKit.framework/PLShortVideoKit (2 slices)
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_PLShortVideoRecorder", referenced from:
      objc-class-ref in YFPostVideoController.o
  "_OBJC_CLASS_$_PLSAudioConfiguration", referenced from:
      objc-class-ref in YFPostVideoController.o
  "_OBJC_CLASS_$_PLSVideoConfiguration", referenced from:
      objc-class-ref in YFPostVideoController.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by HeraShowFeng** [comment]
未包含模拟器 x86_64，但使用模拟器编译 build 导致，建议使用真机设备进行编译调试
