### ISSUE TITLE
[self.recorder startRecording]方法报错

### ISSUE THREAD

**Issue by zhoubo6419** [pili-engineering/PLShortVideoKit#96]
Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[AVAssetWriterInput initWithMediaType:outputSettings:sourceFormatHint:] AVVideoSettings dictionary must specify a positive width'
*** First throw call stack:
(0x1b5f0098c 0x1b5c290a4 0x1bfe46a74 0x1bfe46638 0x102f6a334 0x102f697a4 0x1061aac04 0x1061b9888 0x102f18f6c 0x102f6961c 0x102f02454 0x1061aac04 0x1061b9888 0x102f18f6c 0x102f02178 0x102f020c8 0x102e41bd0 0x1b9f0fa44 0x1b99536d0 0x1b9953a34 0x1b9952a50 0x1b9f48d68 0x1b9f4a0a8 0x1b9f26ae8 0x1b9f9e23c 0x1b9fa0798 0x1b9f9960c 0x1b5e7e7e0 0x1b5e7e738 0x1b5e7ded0 0x1b5e7901c 0x1b5e788bc 0x1bfce4328 0x1b9f0e6d4 0x102e1a1b0 0x1b5d03460)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by Kivenhaoyu** [comment]
麻烦提供下 sdk 的版本、复现设备系统 iOS 版本、本地视频信息（分辨率、帧率）以及时间先动画错误的具体情况描述，我们可根据以上信息做进一步复现排查
