### ISSUE TITLE
强制视频横屏以后，设置视频方向，视频分辨率降低，焦距变近

### ISSUE THREAD

**Issue by dennishappy** [pili-engineering/PLShortVideoKit#99]
强制视频横屏以后，设置视频方向，视频分辨率降低，焦距变近，怎么解决？

**Comment by gdoudeng** [comment]
这个跟videoSize有关

**Comment by yellowMan1** [comment]
> 这个跟videoSize有关

为什么demo我跑不起来 缺少库

**Comment by gdoudeng** [comment]
ShortVideoUIDemo是需要第三方美颜的，如果只需要接入短视频sdk，直接运行ShortVideoFunctionDemo就可以。 @yellowMan1
